export function getMockData() {
  return JSON.stringify(mockData);
}

const mockData = {
  requests: [{
    id: '12345',
    status: 'Needs Approval',
    requestDate: new Date(),
    submittedDate: new Date(),
    name: 'John Doe',
    reqType: 'Translation',
    eventLocation: '123 Main St, Anytown, USA',
    description: 'Requesting translation of syllabus.',
    docLink: 'https://example.com/document',
    docPageCount: 10,
    school: 'Walpole High School',
    originalLanguage: 'English',
    targetLanguage: 'Spanish',
  },
  {
    id: '67890',
    status: 'Completed',
    requestDate: new Date(),
    submittedDate: new Date(),
    name: 'Jane Smith',
    reqType: 'Interpretation',
    eventLocation: '456 Oak Ave, Somewhere, USA',
    description: 'Requesting interpretation services for an upcoming event.',
    startTime: new Date('5/25/2026 6:00 PM'),
    endTime: new Date('5/25/2026 7:00 PM'),
    school: 'Boyden',
    originalLanguage: 'English',
    targetLanguage: 'Chinese',
    approvedBy: 'Admin User',
    approvedDate: new Date('5/15/2026 3:30 PM'),
  },
  {
    id: '67891',
    status: 'Scheduled',
    requestDate: new Date(),
    submittedDate: new Date(),
    name: 'Bob Robertson',
    reqType: 'Interpretation',
    eventLocation: '456 Oak Ave, Somewhere, USA',
    description: 'Requesting interpretation services for an upcoming event.',
    startTime: new Date('6/3/2026 6:00 PM'),
    endTime: new Date('6/3/2026 7:00 PM'),
    school: 'Old Post Road',
    originalLanguage: 'English',
    targetLanguage: 'Portuguese',
    approvedBy: 'Admin User',
    approvedDate: new Date('5/12/2026 2:00 PM'),
  },
  ],
  schools: [
    'Walpole High School',
    'Walpole Middle School',
    'Boyden',
    'Elm Street',
    'Fisher',
    'Old Post Road',
    'Feeney',
    'Central Administration',
    'Student Services',
    'Health Services'
  ],
};