export function getMockData(): string {
  return JSON.stringify(mockData);
}

const mockData: { requests: RawRequest[]; schools: string[]; user: AppUser } = {
  requests: [
    {
      approvedDate: '',
      approverName: '',
      contractor: '',
      contractorName: '',
      description: 'Requesting translation of syllabus',
      docLink: 'https://example.com/document',
      docPageCount: '10',
      email: 'treeve@walpole.k12.ma.us',
      endTime: '',
      eventLocation: '',
      id: 'Item 1',
      interpretationType: '',
      name: 'John Doe',
      originalLanguage: 'English',
      reqType: 'Translation',
      requestDate: '05/28/2026',
      school: 'Walpole High School',
      startTime: '',
      status: 'Needs Approval',
      submittedDate: '05/04/2026 00:00:00',
      targetLanguage: 'Spanish',
      contractorScheduledDate: '',
      documentReturnedDate: '',
      guestConfirmedDate: '',
      techConfirmedDate: '',
    } as RawTranslationRequest,
    {
      approvedDate: '5/1/2026',
      approverName: 'Tom Reeve',
      contractor: 'Lexikeet',
      contractorName: '',
      description: 'Requesting interpretation services for an awards night',
      docLink: '',
      docPageCount: '',
      email: 'treeve@walpole.k12.ma.us',
      endTime: '20:00:00',
      eventLocation: '',
      id: 'Item 2',
      interpretationType: 'One-way presentation',
      name: 'Jane Smith',
      originalLanguage: 'English',
      reqType: 'Interpretation',
      requestDate: '06/03/2026',
      school: 'Boyden',
      startTime: '18:00:00',
      status: 'Complete',
      submittedDate: '05/03/2026 00:00:00',
      targetLanguage: 'Arabic',
      contractorScheduledDate: '5/4/2026',
      documentReturnedDate: '5/5/2026',
      guestConfirmedDate: '5/6/2026',
      techConfirmedDate: '5/7/2026',
    } as RawInterpretationRequest,
    {
      approvedDate: '5/5/2026',
      approverName: 'Tom Reeve',
      contractor: 'Lexikeet',
      contractorName: '',
      description: 'Parent teacher conference',
      docLink: '',
      docPageCount: '',
      email: 'treeve@walpole.k12.ma.us',
      endTime: '12:00:00',
      eventLocation: '',
      id: 'Item 3',
      interpretationType: 'Two-way conversation',
      name: 'Bob Robertson',
      originalLanguage: 'English',
      reqType: 'Interpretation',
      requestDate: '06/17/2026',
      school: 'Student Services',
      startTime: '11:00:00',
      status: 'Scheduled',
      submittedDate: '05/02/2026 00:00:00',
      targetLanguage: 'Vietnamese',
      contractorScheduledDate: '5/5/2026',
      guestConfirmedDate: '',
      techConfirmedDate: '',
    } as RawInterpretationRequest,
    {
      approvedDate: '5/5/2026',
      approverName: 'Tom Reeve',
      contractor: '',
      contractorName: '',
      description: 'Translation of a final exam',
      docLink: 'https://example.com/document',
      docPageCount: '8',
      email: 'treeve@walpole.k12.ma.us',
      endTime: '',
      eventLocation: '',
      id: 'Item 4',
      interpretationType: '',
      name: 'John Doe',
      originalLanguage: 'English',
      reqType: 'Translation',
      requestDate: '05/19/2026',
      school: 'Old Post Road',
      startTime: '',
      status: 'Denied',
      submittedDate: '04/02/2026 00:00:00',
      targetLanguage: 'German',
      contractorScheduledDate: '',
      documentReturnedDate: '',
      guestConfirmedDate: '',
      techConfirmedDate: '',
    } as RawTranslationRequest,
  ],
  schools: [
    'Walpole High School',
    'Walpole Middle School',
    'Boyden',
    'Elm Street',
    'Fisher',
    'Old Post Road',
    'Feeney',
    'Central Administration',
    'Student Services',
  ],
  user: {
    email: 'wpsdeveloper@walpole.k12.ma.us',
    name: 'App Developer',
    role: 'Admin',
    schools: ['Walpole High School', 'Walpole Middle School'],
  },
};
